// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// transition_probabilities
arma::cube transition_probabilities(List Q_eigen, arma::vec edges, int omp);
RcppExport SEXP sfreemapc_transition_probabilities(SEXP Q_eigenSEXP, SEXP edgesSEXP, SEXP ompSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type Q_eigen(Q_eigenSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< int >::type omp(ompSEXP);
    __result = Rcpp::wrap(transition_probabilities(Q_eigen, edges, omp));
    return __result;
END_RCPP
}
// func_H
List func_H(arma::mat Q, List Q_eigen, List tree, List tree_extra, int omp);
RcppExport SEXP sfreemapc_func_H(SEXP QSEXP, SEXP Q_eigenSEXP, SEXP treeSEXP, SEXP tree_extraSEXP, SEXP ompSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< List >::type Q_eigen(Q_eigenSEXP);
    Rcpp::traits::input_parameter< List >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< List >::type tree_extra(tree_extraSEXP);
    Rcpp::traits::input_parameter< int >::type omp(ompSEXP);
    __result = Rcpp::wrap(func_H(Q, Q_eigen, tree, tree_extra, omp));
    return __result;
END_RCPP
}
// posterior_restricted_moment
List posterior_restricted_moment(List tree, List tree_extra, List map, int omp);
RcppExport SEXP sfreemapc_posterior_restricted_moment(SEXP treeSEXP, SEXP tree_extraSEXP, SEXP mapSEXP, SEXP ompSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< List >::type tree_extra(tree_extraSEXP);
    Rcpp::traits::input_parameter< List >::type map(mapSEXP);
    Rcpp::traits::input_parameter< int >::type omp(ompSEXP);
    __result = Rcpp::wrap(posterior_restricted_moment(tree, tree_extra, map, omp));
    return __result;
END_RCPP
}
// fractional_likelihoods
List fractional_likelihoods(List tree, List tree_extra, arma::mat q, List q_eigen, arma::rowvec prior, NumericVector trans_prob, double tol);
RcppExport SEXP sfreemapc_fractional_likelihoods(SEXP treeSEXP, SEXP tree_extraSEXP, SEXP qSEXP, SEXP q_eigenSEXP, SEXP priorSEXP, SEXP trans_probSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< List >::type tree_extra(tree_extraSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type q(qSEXP);
    Rcpp::traits::input_parameter< List >::type q_eigen(q_eigenSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type trans_prob(trans_probSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    __result = Rcpp::wrap(fractional_likelihoods(tree, tree_extra, q, q_eigen, prior, trans_prob, tol));
    return __result;
END_RCPP
}
